export const products = [
    {
        id:1,
        img:"https://images.pexels.com/photos/8837610/pexels-photo-8837610.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        link:"https://www.google.co.in/"
    },
    {
        id:2,
        img:"https://images.pexels.com/photos/7988086/pexels-photo-7988086.jpeg?auto=compress&cs=tinysrgb&w=600",
        link:"https://www.google.co.in/"
    },
    {
        id:3,
        img:"https://images.pexels.com/photos/7213105/pexels-photo-7213105.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
        link:"https://www.google.co.in/"
    },
    {
        id:4,
        img:"https://images.pexels.com/photos/6964348/pexels-photo-6964348.jpeg?auto=compress&cs=tinysrgb&w=600",
        link:"https://www.google.co.in/"
    },
    {
        id:5,
        img:"https://images.pexels.com/photos/6612794/pexels-photo-6612794.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
        link:"https://www.google.co.in/"
    },
    {
        id:6,
        img:"https://images.pexels.com/photos/4443178/pexels-photo-4443178.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
        link:"https://www.google.co.in/"
    },
]